name: Go

on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Check "go mod tidy" was applied
        run: |
          go mod tidy && git status; git diff-index --quiet HEAD --

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Go tests
        run: |
          go test
